### ISSUE TITLE
Python2 end of life

### ISSUE THREAD

**Issue by DaveOri** [igmk/pamtra#15]
Python2 will stop receiving support starting from 1 January 2020
https://pythonclock.org/

This doesn't mean that users will not be able to use pamtra in the near future, just to put a hard limit on the fact that we are still focusing on old technology that will be harder and harder to maintain. We already have numpy old version locks and libgfortran issues with newer versions of anaconda. The side project pamtra2 is already targeting this issue, but I wonder what are the technical limitations in trying to update pyPamtra to py3

**Comment by DaveOri** [comment]
I have tried a new branch [https://github.com/igmk/pamtra/commits/py3Pamtra](py3pamtra).
It is not impossible to have pamtra compiled and sort of running under py3, but the issues we have with numpy version and related packages are not gone and possibly even more difficult to overcome

**Comment by maahn** [comment]
In my opinion the biggest challenge is maintenance. We need at least some basic automatic tests to support two Python versions.

**Comment by DaveOri** [comment]
I also do not think supporting both py2 and py3 is worth the effort. My main motivation were:
> Will it be more and more difficult to maintain the py2 version at all in the future?
> What it takes to convert to py3?
> Will moving to py3 solve our fortran-numpy library version problems? (Downgrading numpy on Ubuntu 18.04 already causes the need to downgrade also matplotlib and netcdf4)

I still think that our main goal should be to move to pamtra2, but I think it was ok to explore what it takes to do the conversion and if there are benefits to do so.

**Comment by maahn** [comment]
I gave it a shot again and adapting PAMTRA to Python 3 was surprisingly easy this time, see the new Python3 branch https://github.com/igmk/pamtra/tree/python3
The major change I had to make was a workaround how to fill the string arrays (e.g. hydro_name) in the descriptor_file module. As a consequence, you might get trouble for >20 hydrometeors, but you can always increase the hardcoded limit (l35 & 36 in descriptor_file.f90)

I tested the branch with examples/pyPamTest_ssrg_hogan2014.py on 
* Mac OS 10.15.6, Python 3.6, Numpy 1.19.1
* Ubuntu Trusty, Python 3.8, Numpy 1.19.1
* Ubuntu Trusty, Python 2.7, Numpy 1.12.1

You can even install the 2.7 and 3.x version side by side, because the names of the compiled libraries are different!

For Ubuntu, see the tools/virtual_machine/install.sh for a working example for a clean system. Pamtra still doesn't work with conda's libgfortran. Note that I did not adapt the other examples to Python 3!

**Comment by maahn** [comment]
I merged the Python 3 branch with the master 1a5b8784d6bb60ddad2817d67fd97d1c1168803c PAMTRA does support Python 2.7 and 3 now.
