### ISSUE TITLE
Vertical wind and particle velocity

### ISSUE THREAD

**Issue by markuskarrer** [igmk/pamtra#26]
The MDV did not fit to the vertical wind speed (W) in regions where W is larger than the terminal velocity. 

![image](https://user-images.githubusercontent.com/20884675/90407706-171a9600-e0a7-11ea-8b8c-90e658d78e63.png)
![image](https://user-images.githubusercontent.com/20884675/90407795-30bbdd80-e0a7-11ea-89a7-12735a80c995.png)

The reason for this seems to be, that the radar_spectrum.f90 W was added to velspec instead of subtracted.

Does this raise issues with radar_airmotion_step_vmin and radar_airmotion_step_vmax?

**Comment by maahn** [comment]
Hi Markus, the sign of the air motion follows the same sign convention as the rest of PAMTRA: down is positive. To be more precise, this is the convention of the fall velocity relations, the rest of PAMTRA doesn’t care. This means model output needs to be multiplied with -1.

I admit that this is poorly documented, but I would not change it to avoid breaking old code and also because I find it confusing if different conventions are used. So I would propose to revert a4725050dfdcde84bccf1302f1e6ad310b7dddfe and improve documentation instead, but I’m open to a better solution. Maybe adding a fall velocity convention switch?

**Comment by DaveOri** [comment]
I am not against reverting a472505 it is just that in this case we we will have to change the icon_meteogram importer (the only one that imports W) and results will change in any case for people that uses it (mostly me and perhaps Claudia ...).
I see the value of not changing the general reference of having velocities going down. This would definitely help to maintain the code since developers will not have to change their way of thinking.
My suggestion is to do like that:
- revert Markus commit
- Modify the importer
- Email users about the modification (they got wrong results in the past)
- document slightly better the situation. Like directly in the relevant code and in the offline documentation

**Comment by markuskarrer** [comment]
I will revert the commit and modify the importer. I think that is a good suggestion considering the violation of old code.
But I think it is also crucial to inform users about the convention. It is very tempting to just pass all the model variables as they are to Pamtra. One really has to be aware of the different convention in PAMTRA compared to (probably all) models, in order to not make this error.

**Comment by maahn** [comment]
I assume this has been fixed with db1c32c5603203adf4e56e97e5ae7644f73be0bb
