### ISSUE TITLE
Radar incidence angle

### ISSUE THREAD

**Issue by VeeramanikandanR** [igmk/pamtra#43]
Hi,
I want to change the radar incidence angle to analyze the bottom-top forward simulated active radar signatures in PAMTRA.
I am particularly interested in studying the sensitivity of mean doppler velocity with the change in bottom-top radar incidence angle.
I am unable to find a namelist parameter for this.
May I know if there is a way to do that?
I am using ssrg-rt3 for ice and snow, and mie-sphere for all the other hydrometeors.
Thanks and Regards,
Veera

**Comment by DaveOri** [comment]
Hi Veera,
so sorry for the late reply, I guess we missed this message, if this happens again, feel free to poke us more.

There is no specific namelist parameter for the radar elevation angle.
Depending on what effect you want to simulate you can achieve it by tweaking the domain, meaning that you actually need to rotate the domain and stretch the range by 1/sin(elevation) to take into account the longer path of the radar beam. Hydrometeor fall velocity and vertical wind must be scaled in a similar way with *cos(elevation).
More complex is the effect of the horizontal wind which generates a radial component as uv*sin(elevation)*cos(alpha) where alpha is the angle (range dependent) between the azimuth of the radar beam and the horizontal wind direction.

All of these effects can be estimated in post processing and are much greater than additional effects that pamtra would be able to calculate if the radar elevation angle and full 3D geometry is taken into account (like the doppler width increase due to the convolution of horizontal wind and beam aperture angle).

If you are interest in only estimating the shift of mdv at different elevation angle I suggest to just scale the vertically pointing mdv with trigonometry

cheers
