### ISSUE TITLE
Error when running simple_passive.ipynb PAMTRA FORTRAN LIBRARY NOT AVAILABLE!

### ISSUE THREAD

**Issue by MichaelAngelPerez** [igmk/pamtra#55]
Hello,
I'm currently trying to run PAMTRA on the NCAR supercomputer Derecho. Running the example code simple_passive.ipynb, yields the following printout when importing
 _PAMTRA FORTRAN LIBRARY NOT AVAILABLE!_
Later on, running
_pam.runParallelPamtra(freqs, pp_deltaX=1, pp_deltaY=1, pp_deltaF=10, pp_local_workers="auto")_
yields
_ImportError: libpmi.so.0: cannot open shared object file: No such file or directory_

Running a simple script I wrote to test the waters yields similar errors pointing to libWrapper.py

In order to get 'make' run without errors, I had to load various modules. I'm not sure if that is the source of the error or if perhaps those modules got reset(I installed it about a month ago and it seemed to be working fine then) but they all seem to be correct.

**Comment by DaveOri** [comment]
Hello Michael,
As a first idea, I would have your same guess. Perhaps modules have been updated, or moved to different locations. The pamtra library looks for shared libraries at runtime and if those are updated it can cause errors. If pamtra was working once, the easiest solution is to try rebuild the package.

The PAMTRA FORTRAN LIBRARY NOT AVAILABLE! error is actually a generic error that is thrown when the python module gets an error while loading pyPamtraLib*.so, it might be caused by many things not necessarily by the modules you had to load (I guess you loaded a compiler like gcc, a blas/lapack implementation like openblas, and libfftw3).

As an example, there might have been changes to the python module (jupyter might run a different kernel now with respect to the one you used to build pyPamtraLib.so). Perhaps you can explore the content of /$HOME/lib/python/pyPamtra (or a different installation target if you set it otherwise), there should be a pyPamtraLib.cpython-<PYVERSION>-<ARCH>-<SO>-<COMPILER>.so; then  load the python module, check that the python version corresponds, run a python console from that folder and try `import pyPamtraLib`, if it throws an error it might be more verbose and hints to the solution.

Those are just random ideas, but the main advice would be to try to rebuild pyPamtraLib

**Comment by MichaelAngelPerez** [comment]
Thank you for the rapid response.
I ran "make clean" and "make" a couple times , reloading various modules and it seems to have worked.
Not entirely sure which module was causing the issue but I suppose that's unimportant.
Thank you!
